In [75]:
import pandas as pd

In [76]:
data = pd.read_csv('IRIS.csv')
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [77]:
selected_columns  = data[['sepal_length','sepal_width']]

selected_columns

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [78]:
filtered_data = data[data['petal_length']>5]

print(filtered_data)
print(filtered_data.shape)

     sepal_length  sepal_width  petal_length  petal_width          species
83            6.0          2.7           5.1          1.6  Iris-versicolor
100           6.3          3.3           6.0          2.5   Iris-virginica
101           5.8          2.7           5.1          1.9   Iris-virginica
102           7.1          3.0           5.9          2.1   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
104           6.5          3.0           5.8          2.2   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
107           7.3          2.9           6.3          1.8   Iris-virginica
108           6.7          2.5           5.8          1.8   Iris-virginica
109           7.2          3.6           6.1          2.5   Iris-virginica
110           6.5          3.2           5.1          2.0   Iris-virginica
111           6.4          2.7           5.3          1.9   Iris-virginica
112           6.8        

In [79]:
grouped_data = data.groupby('sepal_length')['sepal_width'].sum()
grouped_data

sepal_length
4.3     3.0
4.4     9.1
4.5     2.3
4.6    13.3
4.7     6.4
4.8    15.9
4.9    17.2
5.0    31.2
5.1    31.3
5.2    13.7
5.3     3.7
5.4    21.3
5.5    19.9
5.6    16.9
5.7    24.8
5.8    20.2
5.9     9.2
6.0    16.4
6.1    17.1
6.2    11.3
6.3    25.7
6.4    20.7
6.5    15.0
6.6     5.9
6.7    24.4
6.8     9.0
6.9    12.5
7.0     3.2
7.1     3.0
7.2     9.8
7.3     2.9
7.4     2.8
7.6     3.0
7.7    12.2
7.9     3.8
Name: sepal_width, dtype: float64

In [80]:
grouped_data = data.groupby('sepal_width')['sepal_length'].sum()
grouped_data

sepal_width
2.0      5.0
2.2     18.2
2.3     21.3
2.4     15.9
2.5     46.1
2.6     30.8
2.7     52.7
2.8     88.7
2.9     60.6
3.0    156.4
3.1     71.3
3.2     76.5
3.3     36.1
3.4     63.8
3.5     30.9
3.6     16.8
3.7     15.8
3.8     36.6
3.9     10.8
4.0      5.8
4.1      5.2
4.2      5.5
4.4      5.7
Name: sepal_length, dtype: float64

In [81]:
data1 = data[['petal_length','petal_width','species']]
data2 = data[['sepal_length','sepal_width','species']]
print(data1)
print(data2)

     petal_length  petal_width         species
0             1.4          0.2     Iris-setosa
1             1.4          0.2     Iris-setosa
2             1.3          0.2     Iris-setosa
3             1.5          0.2     Iris-setosa
4             1.4          0.2     Iris-setosa
..            ...          ...             ...
145           5.2          2.3  Iris-virginica
146           5.0          1.9  Iris-virginica
147           5.2          2.0  Iris-virginica
148           5.4          2.3  Iris-virginica
149           5.1          1.8  Iris-virginica

[150 rows x 3 columns]
     sepal_length  sepal_width         species
0             5.1          3.5     Iris-setosa
1             4.9          3.0     Iris-setosa
2             4.7          3.2     Iris-setosa
3             4.6          3.1     Iris-setosa
4             5.0          3.6     Iris-setosa
..            ...          ...             ...
145           6.7          3.0  Iris-virginica
146           6.3          2.5  Iris

In [82]:
merged_data = pd.merge(data1,data2,on='species')
print(merged_data)

      petal_length  petal_width         species  sepal_length  sepal_width
0              1.4          0.2     Iris-setosa           5.1          3.5
1              1.4          0.2     Iris-setosa           4.9          3.0
2              1.4          0.2     Iris-setosa           4.7          3.2
3              1.4          0.2     Iris-setosa           4.6          3.1
4              1.4          0.2     Iris-setosa           5.0          3.6
...            ...          ...             ...           ...          ...
7495           5.1          1.8  Iris-virginica           6.7          3.0
7496           5.1          1.8  Iris-virginica           6.3          2.5
7497           5.1          1.8  Iris-virginica           6.5          3.0
7498           5.1          1.8  Iris-virginica           6.2          3.4
7499           5.1          1.8  Iris-virginica           5.9          3.0

[7500 rows x 5 columns]


In [83]:
data.shape

(150, 5)

In [84]:
data.fillna(0,inplace=True)
print(data)


     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [85]:
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [86]:
import numpy as np
data['New_col'] = np.nan

print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     New_col  
0        NaN  
1        NaN  
2        NaN  
3        NaN  


In [87]:
data.fillna(0,inplace=True)
data

sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     New_col  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
..       ...  
145      0.0  
146      0.0  
147      0.0  
148      0.0  
149      0.0  

[150 rows x 6 columns]

In [88]:
data = pd.read_csv('IRIS.csv')

def process_value(value):
    process_value = value*2
    return process_value


data['processed_column'] = data['sepal_length'].apply(process_value)

data

sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_column  
0                10.2  
1                 9.8  
2                 9.4  
3                 9.2  
4                10.0  
..                ...  
145              13.4  
146              12.6  
147              13.0  
148              12.4  
149              11.8  

[150 rows x 6 columns]

In [89]:
pivot_table = pd.pivot_table(data,values='sepal_length',index='sepal_width',columns='species')

print(pivot_table)

species      Iris-setosa  Iris-versicolor  Iris-virginica
sepal_width                                              
2.0                  NaN         5.000000             NaN
2.2                  NaN         6.100000        6.000000
2.3             4.500000         5.600000             NaN
2.4                  NaN         5.300000             NaN
2.5                  NaN         5.625000        5.900000
2.6                  NaN         5.666667        6.900000
2.7                  NaN         5.680000        6.075000
2.8                  NaN         6.150000        6.475000
2.9             4.400000         6.085714        6.800000
3.0             4.700000         5.950000        6.716667
3.1             4.820000         6.766667        6.725000
3.2             4.680000         6.433333        6.760000
3.3             5.050000         6.300000        6.566667
3.4             5.033333         6.000000        6.250000
3.5             5.150000              NaN             NaN
3.6           

In [90]:
data['date_time'] = pd.to_datetime(data['sepal_length'])
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_column                     date_time  
0                10.2

In [91]:
# data = pd.read_csv('IRIS.csv')
data['date_time'] = pd.to_datetime(data['sepal_length'])
data.set_index('date_time',inplace=True)
resambled_data = data.resample('M').sum()

print(resambled_data)

# data

            sepal_length  sepal_width  petal_length  petal_width  \
date_time                                                          
1970-01-31         876.5        458.1         563.8        179.8   

            processed_column  
date_time                     
1970-01-31            1753.0  


C:\Users\PAWAN\AppData\Local\Temp\ipykernel_7860\2977802528.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  resambled_data = data.resample('M').sum()


In [92]:
arr = np.random.randint(1,10,size=10)
arr

array([7, 6, 7, 3, 9, 7, 7, 4, 7, 5])

In [93]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

62
6.2
9
3


In [94]:
arr  = np.arange(27).reshape((3,3,3))
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [95]:
arr = np.random.random((3,3))
print(arr)

[[0.7123265  0.7257208  0.40885357]
 [0.23153062 0.76905633 0.64407697]
 [0.09153537 0.31926373 0.42270762]]


In [96]:
arr1 = np.random.randint(1,10,size=(3,3))
arr2 = np.random.randint(2,20,size=(3,3))
print(arr1)
print(arr2)
result = arr1+arr2
result

[[6 7 7]
 [8 1 2]
 [8 4 1]]
[[ 6  7 17]
 [ 9 19 10]
 [18 16 18]]


array([[12, 14, 24],
       [17, 20, 12],
       [26, 20, 19]])

In [97]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)

[[2 8 5]
 [1 4 7]
 [5 9 3]]


In [98]:
# arr2 = arr.flatten()
# arr2

# arr2 = arr.reshape()

In [99]:
sum_along_rows = np.sum(arr,axis=0)
sum_along_rows

array([ 8, 21, 15])

In [100]:
sum_along_columns = np.sum(arr,axis=1)
sum_along_columns

array([15, 12, 17])

In [102]:
data = np.arange(20)

mask = data>4

filtered_data = data[mask]

print(filtered_data)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [103]:
data = np.array([1,2,23,3,2,3,4,34,3,2,3])

unique_elements = np.unique(data)

element_counts = np.bincount(data)

print(unique_elements)
print(element_counts)

[ 1  2  3  4 23 34]
[0 1 3 4 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1]


In [104]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

coefficients = np.polyfit(x,y,1)

print(coefficients)

[0.6 2.2]


In [105]:
slope,intercept = coefficients

print("Slope",slope)
print("intercept",intercept)

Slope 0.6
intercept 2.199999999999999
